---
apiVersion: v1
kind: Namespace
metadata:
  name: epic-workflow
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: epic-workflow
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdpdC53aWxkYmVycmllcy5ydTo0NTY3Ijogew0KICAgICAgImF1dGgiOiAiY21WbmFYTjBjbmxmYzNaak9uTTBXbE5JVDJkSWQwYzNZdz09Ig0KICAgIH0NCiAgfQ0KfQ==
type: kubernetes.io/dockerconfigjson
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: epic-workflow
  labels:
    name: epic-workflow
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5076
  selector:
    app: web
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: epic-workflow
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: REGISTRY_IMAGE_URL
          ports:
            - containerPort: 5076
              protocol: TCP
          resources:
            requests:
              memory: "600Mi"
              cpu: "400m"
            limits:
              memory: "900Mi"
              cpu: "800m"
          readinessProbe:
            httpGet:
              path: "/alive"
              port: 5076
              httpHeaders:
                - name: Content-Type
                  value: "application/json"
            initialDelaySeconds: 9
            periodSeconds: 6
          livenessProbe:
            httpGet:
              path: "/alive"
              port: 5076
              httpHeaders:
                - name: Content-Type
                  value: "application/json"
            initialDelaySeconds: 10
            periodSeconds: 15
      imagePullSecrets:
        - name: gitlab-registry-secret
